backend:
  name: github
  repo: your_name/repo_name

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "content"
    label: "content"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - {
        label: "Title",
        name: "title",
        widget: "string"
        }
      - {
        label: "Excerpt",
        name: "excerpt",
        widget: "string"
        }
      - {
        label: "Publish Date",
        name: "date",
        widget: "date"
        }
      - {
        label: "Body",
        name: "body",
        widget: "markdown"
        }
